//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS.Resources.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+7 840&lt;/code&gt;
        ///    &lt;name&gt;Abkhazia&lt;/name&gt;
        ///  &lt;/countries&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+93&lt;/code&gt;
        ///    &lt;name&gt;Afghanistan&lt;/name&gt;
        ///  &lt;/countries&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+355&lt;/code&gt;
        ///    &lt;name&gt;Albania&lt;/name&gt;
        ///  &lt;/countries&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+213&lt;/code&gt;
        ///    &lt;name&gt;Algeria&lt;/name&gt;
        ///  &lt;/countries&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+1 684&lt;/code&gt;
        ///    &lt;name&gt;American Samoa&lt;/name&gt;
        ///  &lt;/countries&gt;
        ///  &lt;countries&gt;
        ///    &lt;code&gt;+376&lt;/code&gt;
        ///    &lt;name&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
    }
}
